server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/product_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# This connects the service to Eureka
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka